"""empty message

Revision ID: 4f67fc3f3294
Revises: a5cffa318ac2
Create Date: 2024-05-10 17:23:02.556259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f67fc3f3294'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id_planeta', sa.Integer(), nullable=False),
    sa.Column('nombre_planeta', sa.String(length=100), nullable=False),
    sa.Column('periodo_rotacion', sa.Integer(), nullable=False),
    sa.Column('diametro', sa.Float(), nullable=False),
    sa.Column('clima', sa.String(length=50), nullable=False),
    sa.Column('terreno', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_planeta')
    )
    op.create_table('people',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('nombre_persona', sa.String(length=100), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('color_de_piel', sa.String(length=20), nullable=False),
    sa.Column('color_de_pelo', sa.String(length=20), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_persona')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    op.drop_table('planets')
    # ### end Alembic commands ###
